### ISSUE TITLE
Installing OpenSSH on 5N

### ISSUE THREAD

**Issue by ghost** [droboports/openssh#2]
I've got dropbear install running on port 2222. Trying to install openssh. The install works fine however the service won't start. Here is the contents of the log:

```
2015-10-04 19-00-38: ./service.sh start
+ _service_start
+ _is_running
+ /sbin/start-stop-daemon -K -t -x /mnt/DroboFS/Shares/DroboApps/openssh/sbin/sshd -p /tmp/DroboApps/openssh/pid.txt -q
+ set +x
+ _fix_permissions
+ local devices=/dev/null /dev/full /dev/random /dev/urandom /dev/tty /dev/ptmx /dev/zero /dev/crypto
+ [[ -c /dev/null ]]
+ stat -c %a /dev/null
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/full ]]
+ stat -c %a /dev/full
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/random ]]
+ stat -c %a /dev/random
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/urandom ]]
+ stat -c %a /dev/urandom
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/tty ]]
+ stat -c %a /dev/tty
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/ptmx ]]
+ stat -c %a /dev/ptmx
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/zero ]]
+ stat -c %a /dev/zero
+ [[ 666 -ne 666 ]]
+ [[ -c /dev/crypto ]]
+ [[ ! -f /var/log/lastlog ]]
+ [[ ! -f /etc/login.defs ]]
+ chmod 4711 /mnt/DroboFS/Shares/DroboApps/openssh/libexec/ssh-keysign
+ /mnt/DroboFS/Shares/DroboApps/openssh/sbin/sshd
Privilege separation user sshd does not exist
```

**Comment by ricardopadilha** [comment]
What is the content of `/etc/passwd`? Is there a line starting with `sshd` there?

**Comment by ghost** [comment]
There isn't a sshd user.

```
root:x:0:0:root:/mnt/DroboFS:/bin/sh
nobody:x:99:99:nobody:/:/bin/false
avahi:x:100:100:Avahi Daemon,,,:/:/bin/false
Admin:x:1000:1000:Linux User,,,:/mnt/DroboFS/home/Admin:/bin/sh
```

**Comment by ricardopadilha** [comment]
Yeah, that's strange. All 5N firmwares have an `sshd` user. Which firmware are you on?

**Comment by ghost** [comment]
3.2.3

**Comment by ricardopadilha** [comment]
I think your firmware is somehow messed up. The fact that you are missing the ssh account is an indication that there is something really wrong with it.

I recommend updating to firmware 3.3.0, which will fix your missing sshd account, and also improve your ssh security as well. Just don't forget to update Drobo Dashboard to 2.6.10 while you're at it.

If you prefer, you can also manually reflash 3.2.3 to restore your Drobo to a known good state.

**Comment by ghost** [comment]
Hey thanks for the suggestion. I reset my 5N, updated to 3.3 and openssh works just fine!
